### ISSUE TITLE
How to use this module as perl one liner?

### ISSUE THREAD

**Issue by vodolaz095** [sisimai/rb-Sisimai#146]
I mean, this works somehow in perl

```
$ cat /tmp/sample.eml | perl -MSisimai -lE 'print Sisimai->dump(STDIN)'
$ cat /tmp/sample2.eml | perl -MSisimai -lE 'print Sisimai->dump(STDIN)'
```
but when i try to make similiar thing with ruby, i encounter creepy error like in 
https://github.com/sisimai/rb-Sisimai/issues/61

```
[vodolaz095@steel sisi]$ cat sample2.eml | ruby -rsisimai -e 'puts Sisimai.dump(<STDIN>)'
Traceback (most recent call last):
	16: from <internal:abrt_prelude>:5:in `<internal:abrt_prelude>'
	15: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
	14: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	13: from /usr/share/rubygems/rubygems.rb:213:in `try_activate'
	12: from /usr/share/rubygems/rubygems/specification.rb:1063:in `find_by_path'
	11: from /usr/share/rubygems/rubygems/specification.rb:850:in `stubs'
	10: from /usr/share/rubygems/rubygems/specification.rb:782:in `installed_stubs'
	 9: from /usr/share/rubygems/rubygems/specification.rb:790:in `map_stubs'
	 8: from /usr/share/rubygems/rubygems/specification.rb:790:in `flat_map'
	 7: from /usr/share/rubygems/rubygems/specification.rb:790:in `each'
	 6: from /usr/share/rubygems/rubygems/specification.rb:793:in `block in map_stubs'
	 5: from /usr/share/rubygems/rubygems/specification.rb:768:in `gemspec_stubs_in'
	 4: from /usr/share/rubygems/rubygems/specification.rb:768:in `select'
	 3: from /usr/share/rubygems/rubygems/stub_specification.rb:208:in `valid?'
	 2: from /usr/share/rubygems/rubygems/stub_specification.rb:118:in `data'
	 1: from /usr/share/rubygems/rubygems/stub_specification.rb:118:in `open'
/usr/share/rubygems/rubygems/stub_specification.rb:118:in `initialize': Permission denied @ rb_sysopen - /usr/local/share/gems/specifications/bundler-2.0.1.gemspec (Errno::EACCES)

```

whats wrong here? how can i use ruby module onliner to parse from STDIN?

**Comment by azumakuniyuki** [comment]
One liner examples for reading email data from STDIN are available on https://libsisimai.org/en/usage/#stdin
