### ISSUE TITLE
incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by chahn** [sisimai/rb-sisimai#223]
While parsing several emails following error occurs with Sisimai 4.25.11 and 5-beta2 on ruby 3.0.2p107:

```
/home/chahn/bounce/vendor/bundle/ruby/3.0.0/gems/sisimai-4.25.11/lib/sisimai/reason/rejected.rb:82:in `include?': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
        from /home/chahn/bounce/vendor/bundle/ruby/3.0.0/gems/sisimai-4.25.11/lib/sisimai/reason/rejected.rb:82:in `block in match'
        from /home/chahn/bounce/vendor/bundle/ruby/3.0.0/gems/sisimai-4.25.11/lib/sisimai/reason/rejected.rb:82:in `any?'
        from /home/chahn/bounce/vendor/bundle/ruby/3.0.0/gems/sisimai-4.25.11/lib/sisimai/reason/rejected.rb:82:in `match'
        from /home/chahn/bounce/vendor/bundle/ruby/3.0.0/gems/sisimai-4.25.11/lib/sisimai/reason/rejected.rb:112:in `true'
        from /home/chahn/bounce/vendor/bundle/ruby/3.0.0/gems/sisimai-4.25.11/lib/sisimai/reason.rb:88:in `block in get'
        from /home/chahn/bounce/vendor/bundle/ruby/3.0.0/gems/sisimai-4.25.11/lib/sisimai/reason.rb:76:in `each'
        from /home/chahn/bounce/vendor/bundle/ruby/3.0.0/gems/sisimai-4.25.11/lib/sisimai/reason.rb:76:in `get'
        from /home/chahn/bounce/vendor/bundle/ruby/3.0.0/gems/sisimai-4.25.11/lib/sisimai/data.rb:296:in `make'
        from /home/chahn/bounce/vendor/bundle/ruby/3.0.0/gems/sisimai-4.25.11/lib/sisimai.rb:38:in `make'
        from import.rb:38:in `<main>'
```

I could narrow down the cause to the combination of special characters e.g. `=C3=BC` and an email address in the mail body.
You can reproduce the error with following email:

```
From MAILER-DAEMON  Mon Sep 20 19:29:27 2021
Return-Path: <>
X-Original-To: postmaster@peter.otto.org
Delivered-To: blackhole@localhost
From: <foo@bar.net>
To: postmaster@any.com
Message-ID: <dummy@ott.pet>
Date: Mon, 20 Sep 2021 21:29:21 +0200 (CEST)
X-RZG-CLASS-ID: mi
X-RZG-TRIGGERING-SMTP-ID: qcZaAFivUJ
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable
Subject: kitununulinitoquekegu
In-Reply-To: <foobar@dummy.org>
Auto-Submitted: auto-replied

zuk=C3=BCnftig
karl@hanz.de
```

Thanks for all your great work on sisimai!

**Comment by azumakuniyuki** [comment]
Thanks for the detailed report, I found that this issue also occurs on Ruby 2.6.

```shell
% ruby -v
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]

% ruby -Ilib -rsisimai -e 'puts Sisimai.dump($*.shift)' ./issue-223.eml
Traceback (most recent call last):
	11: from -e:1:in `<main>'
	10: from /Users/ak/workingcopy/rr.nyaan.jp/rb-sisimai/lib/sisimai.rb:70:in `dump'
	 9: from /Users/ak/workingcopy/rr.nyaan.jp/rb-sisimai/lib/sisimai.rb:39:in `rise'
	 8: from /Users/ak/workingcopy/rr.nyaan.jp/rb-sisimai/lib/sisimai/fact.rb:312:in `rise'
	 7: from /Users/ak/workingcopy/rr.nyaan.jp/rb-sisimai/lib/sisimai/reason.rb:70:in `get'
	 6: from /Users/ak/workingcopy/rr.nyaan.jp/rb-sisimai/lib/sisimai/reason.rb:70:in `each'
	 5: from /Users/ak/workingcopy/rr.nyaan.jp/rb-sisimai/lib/sisimai/reason.rb:82:in `block in get'
	 4: from /Users/ak/workingcopy/rr.nyaan.jp/rb-sisimai/lib/sisimai/reason/rejected.rb:109:in `true'
	 3: from /Users/ak/workingcopy/rr.nyaan.jp/rb-sisimai/lib/sisimai/reason/rejected.rb:79:in `match'
	 2: from /Users/ak/workingcopy/rr.nyaan.jp/rb-sisimai/lib/sisimai/reason/rejected.rb:79:in `any?'
	 1: from /Users/ak/workingcopy/rr.nyaan.jp/rb-sisimai/lib/sisimai/reason/rejected.rb:79:in `block in match'
/Users/ak/workingcopy/rr.nyaan.jp/rb-sisimai/lib/sisimai/reason/rejected.rb:79:in `include?': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
```

I will try to debug within a few days

Thanks :-)

**Comment by azumakuniyuki** [comment]
Branch `issue-223` including the fixed code returns the following result:
```json
[
  {
    "catch": "",
    "token": "0da530ae2217e490b990f56b2aed2baced8bd331",
    "lhost": "",
    "rhost": "",
    "alias": "",
    "listid": "",
    "reason": "onhold",
    "action": "",
    "origin": "./issue-223.eml",
    "subject": "",
    "messageid": "",
    "replycode": "",
    "smtpagent": "RFC3464",
    "softbounce": 1,
    "smtpcommand": "",
    "destination": "hanz.de",
    "senderdomain": "any.com",
    "feedbacktype": "",
    "diagnosticcode": "zukünftig karl@hanz.de",
    "diagnostictype": "",
    "deliverystatus": "5.0.901",
    "timezoneoffset": "+0200",
    "addresser": "postmaster@any.com",
    "recipient": "karl@hanz.de",
    "timestamp": 1632166161
  }
]
```

**Comment by azumakuniyuki** [comment]
@chahn Would you give us allow to add the email you attached to https://github.com/sisimai/set-of-emails and `set-of-emails` directory of each repository as a sample?

Best regards,

**Comment by chahn** [comment]
@azumakuniyuki the branch `issue-223` fixed the issue in my test.
Yes, of course you can use the provided email as a sample in each repository.

Thanks a lot for helping with this issue!

**Comment by azumakuniyuki** [comment]
@chahn Thank you for your acceptance :-)
