### ISSUE TITLE
Sisimai.dump(STDIN) does not work properly

### ISSUE THREAD

**Issue by azumakuniyuki** [sisimai/rb-Sisimai#67]
<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">そういえばSisimaiという便利なバウンスメールパーサーをみつけたけど、なぜかrubyのSTDINが動かず、、ぐぬぬ。</p>&mdash; まりねっち / ようゴソ / yaoki (@marine_dayo) <a href="https://twitter.com/marine_dayo/status/835118401718648833">February 24, 2017</a></blockquote>

```shell
% cat ./set-of-emails/maildir/bsd/mta-postfix-01.eml | ruby -Ilib -rsisimai -e 'puts Sisimai.dump(STDIN)'
/Users/ak/localrepos/rr.nyaan.jp/rb-Sisimai/lib/sisimai.rb:99:in `make':  ***error: invalid value of "input" (RuntimeError)
	from /Users/ak/localrepos/rr.nyaan.jp/rb-Sisimai/lib/sisimai.rb:118:in `dump'
	from -e:1:in `<main>'

```

**Comment by azumakuniyuki** [comment]
Fixed at v4.20.2
